---
# tasks file for jenkins
- name: Install jenkins 
  script: jenkins.sh 
  notify:
    - Restart Jenkins

- name: Ensure Jenkins service is enabled and started
  systemd:
    name: jenkins
    state: started
    enabled: yes
    
- name: Get Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password


- name: Print Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"




# my_jenkins_role/tasks/main.yml
- name: Retrieve Jenkins Credential
  script: |
    jenkins_cli="{{ jenkins_cli_path }}"
    jenkins_url="{{ jenkins_url }}"
    credential_id="{{ credential_id }}"

    groovy_script = '''
        def password = hudson.util.Secret.toString(
            hudson.model.Hudson.instance
                .getDescriptorByType(com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl.DescriptorImpl.class)
                .getCredentials()
                .find { it.id == "$credential_id" }
                .getPassword()
        )
        println(password)
    '''

    password = sh(script: "${jenkins_cli} groovy = <<<'${groovy_script}'", returnStdout: true).trim()
    echo "Password: ${password}"
  when: ansible_os_family == 'Linux'

